### ISSUE TITLE
using custom key prefix

### ISSUE THREAD

**Issue by mehdy** [boj/redistore#22]
why doesn't it get the key prefix dynamically?

**Comment by headwindfly** [comment]
It provides method to set custom prefix:
```
// SetKeyPrefix set the prefix
func (s *RediStore) SetKeyPrefix(p string) {
	s.keyPrefix = p
}
```

**Comment by mehdy** [comment]
thanks! but I think it would be better to set it when creating RedisStore

**Comment by elithrar** [comment]
> thanks! but I think it would be better to set it when creating RedisStore

That's exactly what you should do: create the store, and call `SetKeyPrefix` as soon as you have a Store object to modify.

```go
store, err := NewRediStore(10, "tcp", ":6379", "", []byte("secret-key"))
if err != nil {
    return err
}
defer store.Close()

store.SetKeyPrefix("prefix")

// Rest of your code
```

**Comment by mehdy** [comment]
Thanks
