### ISSUE TITLE
Why response Set-Cookie header every time when save session?

### ISSUE THREAD

**Issue by jaggerwang** [boj/redistore#23]
I only want to save session data to redis, and the cookie, which contain session id, is not changed, there is no need to set cookie again. Set cookie only need once when a new session is created.

**Comment by elithrar** [comment]
This is possible, but you would need to take into account:

1. If the session is close to expiration, do you Set-Cookie?
2. If the Redis data expired, you would need to Set-Cookie with the new ID
3. Making it optional, which is not possible with the sessions.Store
interface.

How often are you changing the session data, and is the overhead of the
Set-Cookie call a major issue?

**Comment by jaggerwang** [comment]
1. If session is expired, client, such as browser, will not send previous saved cookie anymore. A new session should be created in the next request.
2. If redis data expired, a new session will be created, and should set cookie.
There is no much performace problem, I just found it not same with previously used session lib.

I'm using Echo web framework, and write a middleware to responsible for session creating and saving. Am I using it the right way?
```go
package middlewares

import (
	log "github.com/Sirupsen/logrus"
	"github.com/labstack/echo"
	"github.com/labstack/echo/engine/standard"
	"github.com/spf13/viper"
	"gopkg.in/boj/redistore.v1"

	"zaiqiuchang.com/server/models"
)

func Session() echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) (err error) {
			store, err := redistore.NewRediStoreWithPool(
				models.RedisPool("zqc"), []byte(viper.GetString("secretkey")))
			if err != nil {
				panic(err)
			}
			defer store.Close()
			store.SetMaxAge(viper.GetInt("session.maxAge"))
			store.SetMaxLength(viper.GetInt("session.maxLength"))
			store.SetKeyPrefix(viper.GetString("session.keyPrefix"))
			req := c.Request().(*standard.Request)
			session, err := store.Get(req.Request, viper.GetString("session.name"))
			if err != nil {
				panic(err)
			}
			c.Set("session", session)

			err = next(c)

			if session.IsNew || c.Get("sessionModified") != nil {
				values := map[string]interface{}{}
				for k, v := range session.Values {
					values[k.(string)] = v
				}
				log.WithFields(log.Fields{
					"id":     session.ID,
					"isNew":  session.IsNew,
					"values": values,
				}).Debug("save session")
				rsp := c.Response().(*standard.Response)
				if err := session.Save(req.Request, rsp.ResponseWriter); err != nil {
					log.Error(err)
				}
			}

			return err
		}
	}
}
```

**Comment by elithrar** [comment]
1. Correct, but the *package user* may expect that the Redis data is kept
in sync with the session cookie. Not refreshing the cookie but refreshing
Redis is non-obvious.

**Comment by jaggerwang** [comment]
That's right, but it's still no need to refresh cookie every time when saving to redis. Only do this when cookie changed, including value, expire time, path, etc.

**Comment by elithrar** [comment]
Of course, but I would argue that use-case—constantly updating the
cookie—is much rarer. Users have also come to rely on the existing
behavior.

You are welcome to submit a PR that (without breaking existing behavior)
can achieve this.

**Comment by boj** [comment]
Marking this as closed.
