### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by sloweclair** [boj/redistore#26]
Right now every get or set pings the redis server first. This adds some latency to it. Any reason for this?

**Comment by boj** [comment]
You'll have to dig around the upstream libraries for that answer.

**Comment by kisielk** [comment]
Actually I think it's because the pool is set up to ping with `TestOnBorrow` unconditionally. It should check the last time the connection was idle, like in the examples in redigo.

**Comment by boj** [comment]
Reopen if necessary.
