### ISSUE TITLE
custom structs missing from GOB will silently fail and return sessions without some values.

### ISSUE THREAD

**Issue by antihax** [boj/redistore#27]
The error from `s.load(session)` is out of scope of the return and will silently fail to deserialize custom structs missing from gob and stored in values.

Replication:
1. `gob.Register(oauth2.Token{})`
2. save an `oauth2.Token{}` structure to a session.Values
3. remove `gob.Register(oauth2.Token{})`
4. Attempt to read the value again. Valid session returned, no error given, and values beyond are not deserialized.

```
// New returns a session for the given name without adding it to the registry.
//
// See gorilla/sessions FilesystemStore.New().
func (s *RediStore) New(r *http.Request, name string) (*sessions.Session, error) {
	var err error

	session := sessions.NewSession(s, name)
	// make a copy
	options := *s.Options
	session.Options = &options
	session.IsNew = true
	if c, errCookie := r.Cookie(name); errCookie == nil {
		err = securecookie.DecodeMulti(name, c.Value, &session.ID, s.Codecs...)
		if err == nil {
			*ok, err := s.load(session)*
			session.IsNew = !(err == nil && ok) // not new if no error and data available
		}
	}
	return session, err
}
```

**Comment by boj** [comment]
@antihax Thanks for the report. Unfortunately I don't have the bandwidth to work on this anymore, but am happy to take a patch which fixes the behavior.

**Comment by antihax** [comment]
No problem, check #28
