### ISSUE TITLE
Allow passthrough of `DialOptions`

### ISSUE THREAD

**Issue by adborden** [boj/redistore#29]
The initial connect timeout is too slow for us, so we'd like to be able to pass a connection timeout to the redis store.  This should be pretty straight forward with [redis.Dial](https://godoc.org/github.com/garyburd/redigo/redis#Dial) which allows a `DialOptions` as a third parameter which can be used to specify the connection timeout in addition to some other goodies.

**Comment by boj** [comment]
@adborden If you could submit a PR with this behavior that would be great.

**Comment by antihax** [comment]
I think you can do this already with `NewRediStoreWithPool`?

**Comment by boj** [comment]
Reopen if necessary.
