### ISSUE TITLE
gob: decoding into local type *string, received remote type map[interface]interface

### ISSUE THREAD

**Issue by chances** [boj/redistore#31]
I've hit a wall with this error after attempting to load a key from the session. I'm using [gin-contrib/sessions](https://github.com/gin-contrib/sessions) which "thinly" wraps around redistore and gorilla/sessions. I create the Redis Store using [a pre-existing pool](https://github.com/chances/chances-party/blob/golang/session.go#L34) and then utilize the session when handling authentication:

```go
session.Set("AUTH_STATE", state)
session.Save()
```

In an OAuth callback handler I attempt to load the `AUTH_STATE` from the session ([source](https://github.com/chances/chances-party/blob/golang/auth.go#L57-L63)):

```go
v := session.Get("AUTH_STATE")
if v == nil {
  c.Error(errAuth.WithDetail("Auth state is nil"))
  c.Abort()
  return
}
```

The value is always `nil`. Though it seems the error occurs whenever the session is attempts to load at the beginning of every handler after the session is created.

I noticed @boj encountered this error [while creating this project](https://plus.google.com/109959252696929013483/posts/eF4aykYhnef), but has since resolved the problem.

I've been banging my head on the table for days over this. I'd greatly appreciate any assistance.

**Comment by shkim** [comment]
I suffered the same problem.
Only strings could be retrieved from the session; otherwise nil.

**Comment by chances** [comment]
@shkim In my case, the only thing attempting to be retrieved is a string, but it's always nil.

I can see the value was saved when I look directly at the Redis server.

**Comment by boj** [comment]
@chances @shkim I haven't worked on a Go project for 2 years now, and simply handle the random incoming PR these days. Sorry I can't offer any help. If you do come up with a solution I'd be happy to take a PR and merge it in.

**Comment by boj** [comment]
Feel free to open a new issue if this is still a problem.
