### ISSUE TITLE
Propagate `gob/encoding` errors.

### ISSUE THREAD

**Issue by njnygaard** [boj/redistore#33]
I was getting an error in my code that I only discovered after debugging [this](https://github.com/boj/redistore/blob/master/redistore.go#L245) line. The error here was: `gob: name not registered for interface: ...`. 

I understand that it is my issue that I did not register my type with `gob` at the time that I tried to access the value in the session, but it was not intuitive and there was no error thrown in my face.

We can close the issue if we determine that I am sufficiently bad at this.

**Comment by kisielk** [comment]
I'm not sure I understand. The error is returned on line 249.

**Comment by njnygaard** [comment]
As I am new to go, is there a scoping error for the identifier `err`? I was debugging and noticed that a print statement near the line I specified resulted in seeing the error:
```
REDISTORE: ok? true
REDISTORE: err? gob: name not registered for interface: "gitlab.com/droneprime/spectre.host/server/internal/handlers.User"
```

But over on my code side I saw stuff like this:
```
2017/07/19 11:32:06 Here's what I see. <nil>
2017/07/19 11:32:06 The session was new, here's what I see. &{0         }
2017/07/19 11:32:06 The session was new, here's what I see. OF3DWYGSPW7SGTSA4WKCLMACQQWHQA4LGRNFMZ24I5D7LYFTL7PA
2017/07/19 11:32:06 The session was new, here's what I see. true
2017/07/19 11:32:06 Tried to get the current user from the session store. Failed {0         }
```
(sorry for the almost non-sensical debug log. I can make a cleaner one if you need.)

Because of the prescence of `err`, `IsNew` was set to `true` when it did indeed find the key in redis.

**Comment by kisielk** [comment]
`err` is scope for the full function, because it's declared on line 243, and then not shadowed in any of the other scopes. I can't tell what you're doing without seeing the code.

**Comment by njnygaard** [comment]
```
func (s *RediStore) New(r *http.Request, name string) (*sessions.Session, error) {
	var err error
	session := sessions.NewSession(s, name)
	// make a copy
	options := *s.Options
	session.Options = &options
	session.IsNew = true
	if c, errCookie := r.Cookie(name); errCookie == nil {
		err = securecookie.DecodeMulti(name, c.Value, &session.ID, s.Codecs...)
		if err == nil {
			ok, err := s.load(session)
			session.IsNew = !(err == nil && ok) // not new if no error and data available
		}
	}
	return session, err
}
```
This is my code. Note: `:=` at the `s.load` call. That's clearly been changed for the line I linked in the first issue comment.
I guess I shouldn't complain without updating huh?
My lib repo is at `fc113767cd6b051980f260d6dbe84b2740c46ab0`

**Comment by njnygaard** [comment]
Closing as out of date.

**Comment by njnygaard** [comment]
https://github.com/boj/redistore/pull/28
