### ISSUE TITLE
Enhancement request to extend session automatically during use

### ISSUE THREAD

**Issue by devnull52** [boj/redistore#36]
As I understand, with the current implementation irrespective of usage, the session times out at a set time. Similar to Java based session implementation, would it be possible to extend the expiration of session during continuous use? I hope this is the right way to request an enhancement request.

**Comment by dsoprea** [comment]
It might be best to bring this up with gorilla/sessions. If this was the case, it should be fixed there so that it would be a proper, general solution and not a backend-specific one.

If you're in a tight-spot, the poor-man's solution (in spite of what I just said) is to put that logic in `load()`.

**Comment by kisielk** [comment]
Actually gorilla/seasions#105 would be the perfect place to mention this.

**Comment by elithrar** [comment]
Calling session.Save again will reset the TTL on the session automatically.

The Save method of this store calls the private save() method -
https://github.com/boj/redistore/blob/master/redistore.go#L310

Doing that automatically on a Get may not be ideal, and you may want to
avoid doing that.

If you want it to be automatic for your application, write middleware that
calls Save at the end of a request, before the response body is written.

**Comment by dsoprea** [comment]
Thanks for mentioning that.

You have your answer, @devnull.
