### ISSUE TITLE
IsNew access on a session causes nil pointer dereference

### ISSUE THREAD

**Issue by Nexterot** [boj/redistore#49]
After getting a session from RediStore via Get method and checking its IsNew property, I get nil pointer dereference error. Docs refer to gorilla's FileSystemStore, which also refers to CookieStore, so that http://www.gorillatoolkit.org/pkg/Sessions#CookieStore.Get says:

> Access IsNew on the session to check if it is an existing session or a new one.

<br>
P.S. my code worked well before changing backend from gorilla's CookieStore to RediStore.

**Comment by elithrar** [comment]
Can you show the code that exhibits this behaviour / provide a reproducible
example?

**Comment by Nexterot** [comment]
Lots of sorry for disturbing, man, that was only my own fault with accessing another nil variable. Take a star
